server:
  port: 8080
  # 웹 애플리케이션을 구분할 때 사용
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true # 콘솔창에 sql 출력
    properties:
      hibernate:
        format_sql: true # 콘솔창에 출력되는 SQL문을 사람이 보기 편한 형태로 출력
        default_batch_fetch_size: 500 # 1:N 컬렉션 조회 시 성능 최적화
    open-in-view: false # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정

  servlet:
    multipart:
      max-file-size: 10MB # 파일 업로드 요청 시 하나의 파일 크기를 10MB로 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일의 크기 합을 100MB로 제한

logging:
  level:
    org.hibernate.type: trace # 콘솔창에 출력되는 SQL문에 ?가 아닌 조건에 바인딩 되는 값 및 조회 결과 출력
    com.app: debug # todo 패키지 수정

feign:
  client:
    config:
      default:
        connect-timeout: 5000 # 5초
        read-timeout: 5000 # 5초

